; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

; Common settings for all environments
[env]
monitor_speed = 115200
extra_scripts = pre:load_env.py
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    knolleary/PubSubClient@^2.8
framework = arduino

; ESP32 Development Board
[env:esp32dev]
platform = espressif32
board = esp32dev

; ESP8266 NodeMCU v3
[env:nodemcuv3]
platform = espressif8266
board = nodemcuv2
